# Generated by Django 3.0.1 on 2019-12-30 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CallAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('s_no', models.IntegerField()),
                ('issue', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=1)),
                ('estimate_hours', models.FloatField()),
                ('status', models.CharField(choices=[(11, 'Not Yet'), (12, 'In Progress'), (13, 'On hold'), (14, 'Completed')], max_length=1)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('remarks', models.CharField(max_length=2000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Engineer')),
            ],
        ),
    ]
