# Generated by Django 3.0.1 on 2020-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[('Not Yet', 'NotYet'), ('in_progress', 'In Progress'), ('on_hold', 'On hold'), ('completed', 'Completed')], max_length=15),
        ),
    ]
