# Generated by Django 3.0.1 on 2020-01-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(blank=True, choices=[('not_yet', 'Not Yet'), ('in_progress', 'In Progress'), ('on_hold', 'On hold'), ('completed', 'Completed')], max_length=15),
        ),
    ]
