# Generated by Django 3.0.1 on 2020-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200119_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[('Not-Yet', 'not_yet'), ('In-Progress', 'in_progress'), ('On-Hold', 'on_hold'), ('Completed', 'completed')], max_length=15),
        ),
    ]
