# Generated by Django 3.0.1 on 2020-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200105_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
