# Generated by Django 3.0.1 on 2020-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200119_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[('Not-Yet', 'Not-Yet'), ('In-Progress', 'In-Progress'), ('On-Hold', 'On-Hold'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
