# Generated by Django 3.0.1 on 2020-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
