# Generated by Django 3.0.1 on 2020-01-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200105_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='remarks',
            field=models.TextField(max_length=2000),
        ),
    ]
