# Generated by Django 3.0.1 on 2020-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200105_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='s_no',
            field=models.IntegerField(blank=True),
        ),
    ]
