# Generated by Django 3.0.1 on 2020-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200206_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[(1, 'Not-Yet'), (2, 'In-Progress'), (3, 'On-Hold'), (4, 'Completed')], max_length=15),
        ),
    ]
