# Generated by Django 3.0.1 on 2020-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200206_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[('Not-Yet', 'Not-Yet'), ('In-Progress', 'In-Progress'), ('On-Hold', 'On-Hold'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
