# Generated by Django 3.0.1 on 2020-02-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20200206_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='callallocation',
            name='actual_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
