# Generated by Django 3.0.1 on 2020-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20200105_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
