# Generated by Django 3.0.1 on 2020-01-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20200109_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
