# Generated by Django 3.0.1 on 2020-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_delete_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Yet', 'not_yet'), ('in_progress', 'In Progress'), ('on_hold', 'On hold'), ('completed', 'Completed')], max_length=15),
        ),
    ]
