# Generated by Django 3.0.1 on 2020-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20200111_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='callallocation',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
