# Generated by Django 3.0.1 on 2020-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20200112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='status',
            field=models.CharField(choices=[('not_yet', 'NotYet'), ('in_progress', 'In Progress'), ('on_hold', 'On hold'), ('completed', 'Completed')], max_length=15),
        ),
    ]
