# Generated by Django 3.0.1 on 2020-01-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20200112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
