# Generated by Django 3.0.1 on 2020-01-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20200112_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callallocation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
